# ─────────────────────────────────────────────
# utils/file_exporter.py — Report Exporter
# Converts markdown reports to styled HTML
# ─────────────────────────────────────────────

import os
import markdown
from datetime import datetime
import re

def save_report_to_html(query: str, markdown_content: str) -> str:
    """
    Converts a Markdown report to a beautifully styled HTML file and saves it to disk.
    
    Args:
        query: The user's original search query (used for filename)
        markdown_content: The raw markdown text of the report
        
    Returns:
        The absolute path to the saved HTML file
    """
    # Create reports directory if it doesn't exist
    reports_dir = os.path.join(os.getcwd(), "reports")
    os.makedirs(reports_dir, exist_ok=True)
    
    # Generate safe filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_query = re.sub(r'[^a-zA-Z0-9]', '_', query.lower())[:30] # Keep it short and safe
    filename = f"{timestamp}_{safe_query}.html"
    filepath = os.path.join(reports_dir, filename)
    
    # Convert markdown to HTML
    # We enable 'fenced_code' and 'tables' extensions for better formatting
    html_body = markdown.markdown(markdown_content, extensions=['fenced_code', 'tables'])
    
    # Professional CSS Styling
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Research Report: {query}</title>
        <style>
            :root {{
                --primary: #2563eb;
                --text-main: #1f2937;
                --bg-main: #f8fafc;
                --card-bg: #ffffff;
                --border: #e2e8f0;
            }}
            body {{
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                line-height: 1.6;
                color: var(--text-main);
                background-color: var(--bg-main);
                margin: 0;
                padding: 40px 20px;
            }}
            .container {{
                max-width: 800px;
                margin: 0 auto;
                background-color: var(--card-bg);
                padding: 40px;
                border-radius: 12px;
                box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
            }}
            h1, h2, h3 {{
                color: #111827;
                margin-top: 2em;
                margin-bottom: 0.5em;
            }}
            h1 {{
                font-size: 2.25rem;
                margin-top: 0;
                color: var(--primary);
                border-bottom: 2px solid var(--primary);
                padding-bottom: 10px;
            }}
            a {{
                color: var(--primary);
                text-decoration: none;
            }}
            a:hover {{
                text-decoration: underline;
            }}
            code {{
                background-color: #f1f5f9;
                padding: 0.2em 0.4em;
                border-radius: 4px;
                font-size: 0.9em;
                font-family: monospace;
            }}
            pre {{
                background-color: #1e293b;
                color: #f8fafc;
                padding: 16px;
                border-radius: 8px;
                overflow-x: auto;
            }}
            pre code {{
                background-color: transparent;
                color: inherit;
                padding: 0;
            }}
            blockquote {{
                border-left: 4px solid var(--primary);
                margin: 0;
                padding-left: 16px;
                color: #475569;
                background-color: #f1f5f9;
                padding: 10px 16px;
                border-radius: 0 8px 8px 0;
            }}
            ul, ol {{
                padding-left: 24px;
            }}
            li {{
                margin-bottom: 8px;
            }}
            .footer {{
                margin-top: 40px;
                text-align: center;
                font-size: 0.875rem;
                color: #64748b;
                border-top: 1px solid var(--border);
                padding-top: 20px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="report-content">
                {html_body}
            </div>
            <div class="footer">
                Generated by Autonomous Multi-Agent Research Assistant &bull; {datetime.now().strftime("%B %d, %Y %H:%M")}
            </div>
        </div>
    </body>
    </html>
    """
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html_template)
        
    print(f"\n[Exporter] Report saved as HTML to: {filepath}")
    return filepath
